# Generated by Django 3.0.4 on 2020-03-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NorthMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SouthMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('season', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameField(
            model_name='critter',
            old_name='start_time',
            new_name='timeframe',
        ),
        migrations.RemoveField(
            model_name='critter',
            name='end_time',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.AddField(
            model_name='southmonth',
            name='critters',
            field=models.ManyToManyField(to='crit.Critter'),
        ),
        migrations.AddField(
            model_name='northmonth',
            name='critters',
            field=models.ManyToManyField(to='crit.Critter'),
        ),
    ]
