# Generated by Django 3.0.4 on 2020-03-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crit', '0003_auto_20200328_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='critter',
            name='family',
            field=models.CharField(default='null', max_length=200),
        ),
    ]
