# Generated by Django 3.0.4 on 2020-03-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crit', '0006_auto_20200328_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('shadow', models.CharField(max_length=200)),
                ('timeframe', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Insect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('timeframe', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='northmonth',
            name='fish',
            field=models.ManyToManyField(to='crit.Fish'),
        ),
        migrations.AddField(
            model_name='northmonth',
            name='insect',
            field=models.ManyToManyField(to='crit.Insect'),
        ),
        migrations.AddField(
            model_name='southmonth',
            name='fish',
            field=models.ManyToManyField(to='crit.Fish'),
        ),
        migrations.AddField(
            model_name='southmonth',
            name='insect',
            field=models.ManyToManyField(to='crit.Insect'),
        ),
    ]
